### ISSUE TITLE
Very helpful and most completed Jotform Library

### ISSUE THREAD

**Issue by mohummedibrahim** [Hona/Jotform.NET#1]
Hi @Hona, thanks for making this library available, this is so far the most complete, better replacement of an existing outdated Jotform SDK (in c#) I could find. 

I'm wondering if it would be possible to make a few changes/updates or accept the PRs?  Some of the changes I've already made and would like to contribute.
- The `JotformClient` is currently initiating the `HttpClient`, which makes it difficult to control the client's lifetime, I will suggest injecting it in the constructor instead.
- Some of the APIs support filter (in json string format), but the filter commands are not completely documented, and error-prone to write, a `JotformFilterBuilder` class could be convenient.
- Most of the GET methods in Endpoints folder are just a wrapper around GetFromJsonAsync, the async/await keywords can be removed for improving some allocations.

https://github.com/mohummedibrahim/Jotform.NET/commit/690cda9097a0e941028c707faf79567e1677d8fb

Please let me know as time permits. 

Thanks again!

**Comment by Hona** [comment]
Hi @mohummedibrahim,

Thanks for finding and using my library!

I'm always willing to accept community PRs, so feel free to submit them and I'll review them as they come through. 

Flipping the HttpClient to be injected in is all great. 

The additional filtering capabilities also sound and look pretty good to me. 

As for the async stuff, provided there is basically just a one line await, it's fine to return the task directly. 

Thanks again :)

**Comment by mohummedibrahim** [comment]
Thanks for the quick response. I've just added the PR https://github.com/Hona/Jotform.NET/pull/2

**Comment by Hona** [comment]
@mohummedibrahim 

#2  is now merged, let me know whenever you'd like a nuget release, or any assistance. I'd be happy to help out :)

**Comment by mohummedibrahim** [comment]
Thanks so much!

I've a few more changes to add, will let you know once I'm done with PRs (hopefully within a few days to week) . And it would be super helpful if you can then release an updated nuget version.

Thanks again!

**Comment by Hona** [comment]
Thanks @mohummedibrahim, I've approved & merged your PR :)

Let me know whenever the next one is ready, or when you want the NuGet release 🚀

**Comment by mohummedibrahim** [comment]
Thanks so much for merging the last one.
Just added https://github.com/Hona/Jotform.NET/pull/4

**Comment by Hona** [comment]
Nice PR, just got some questions with that `#nullable disable` stuff, left in the PR

@mohummedibrahim

**Comment by Hona** [comment]
@mohummedibrahim Both those PRs are now merged - did you want me to release it on NuGet or was there more to come? :D

**Comment by mohummedibrahim** [comment]
@Hona Thanks so much for getting these merged. Yes, please release the updated NuGet, it would be very helpful for me now.

**Comment by Hona** [comment]
Awesome, you did a heap of great work! 

I have done the prep work + published the version `1.1.0` to NuGet, it should be available for search shortly:

![image](https://github.com/user-attachments/assets/3235fa63-a3d0-4588-8ea2-bb33a9f42fbb)

**Comment by mohummedibrahim** [comment]
Thank you so much! 

This library indeed is a BIG help for me and already saved me a lot of time.

**Comment by Hona** [comment]
Glad to hear.

I'll close this issue for now since it seems like everything you need is done?
