### ISSUE TITLE
The Status property could have a value "ARCHIVED"

### ISSUE THREAD

**Issue by mohummedibrahim** [Hona/Jotform.NET#5]
Currently, we have a `Status` enum that follows exactly the Jotform API docs e.g.

`
public enum Status
{
    Active,
    Deleted,
    Suspended,
    OverQuota,
    Live,
    Pending,
    Enabled,
    Disabled,
    RanToCompletion
}
`

But it looks like there's one more "ARCHIVED",  which they've not documented anywhere. While retrieving the UserFormSubmissions I got an exception that JsonSerializer couldn't serialize the status. The logger gets me this.

![image](https://github.com/user-attachments/assets/645bcbd9-f276-4836-a42b-9e5516508b0f)

Reported for tracking. I'll get this status added.

**Comment by Hona** [comment]
I've noticed the Jotform API docs are fairly lacking - nice catch! :)
