### ISSUE TITLE
The Status (Enum) property needs to be guarded against unknown values.

### ISSUE THREAD

**Issue by mohummedibrahim** [Hona/Jotform.NET#7]
Hi @Hona, hope all is well!

In https://github.com/Hona/Jotform.NET/pull/6 I attempted to fix https://github.com/Hona/Jotform.NET/issues/5 but it seems there're more of that, e.g. here is one I saw today "CUSTOM".

![image](https://github.com/user-attachments/assets/63ca3b4c-31b0-4c25-8935-a0b93ee640e3)

Because of this, the JSON serializer throws this 
`The JSON value could not be converted to Jotform.Models.Shared.Status. Path: $.content[75].status | LineNumber: 0 | BytePositionInLine: 208434`

On top of my head, I can think of a few solutions, please let me know which one you prefer, and I'll get that added. 
1. For now, add a value "CUSTOM" to the Status enum.
2. Add "Unknown" as a fallback to the enum and map all unknown values to it via a custom converter.
3. Better to do both 1 & 2.
4. Change the property type from enum to string.

Or, please let me know if you prefer something else, 

Thanks!

**Comment by Hona** [comment]
Hey @mohummedibrahim,
Thanks for the new issue :)

I'd stick with just adding the new enum value Custom for now.

It should throw an exception when an unknown value, and a complete enum with values is a nice developer experience.

We can add new values as they appear

**Comment by mohummedibrahim** [comment]
Sounds great! I will get that added.

**Comment by Hona** [comment]
Thank you for the fix @mohummedibrahim :)

The NuGet version is uploaded at https://www.nuget.org/packages/Jotform.NET/1.1.1

**Comment by mohummedibrahim** [comment]
Thanks so much!
